#![no_std]

//! Skyhitz Core V1 - Soroban Smart Contract
//!
//! Purpose: Record user actions for music entries, reward users with HITZ tokens,
//! attribute XLM fees to entries, and manage HITZ staking for invest/mine actions.
//!
//! HITZ Token:
//! - OpenZeppelin SEP-41 compatible fungible token with fixed cap: 21,000,000 HITZ
//! - Token handles its own emission logic with Bitcoin-style halving schedule
//! - This contract requests rewards from the token based on action difficulty
//!
//! XLM Fees:
//! - All XLM fees are transferred to Treasury address (market-making bot for liquidity)
//! - Contract does not swap or interact with AMMs
//!
//! Action Kinds & Parameters (fees calculated as base_fee * difficulty):
//! - stream:   difficulty 1,  fee = base_fee × 1  (default 0.01 XLM), adds to escrow
//! - like:     difficulty 2,  fee = base_fee × 2  (default 0.02 XLM), adds to escrow
//! - download: difficulty 3,  fee = base_fee × 3  (default 0.03 XLM), adds to escrow
//! - mine:     difficulty 10, fee = base_fee × 10 (default 0.1 XLM), adds to TVL, auto-stakes
//! - invest:   DYNAMIC fee (min 0.3 XLM), proportional difficulty (10 per 1 XLM), adds to TVL, auto-stakes
//!
//! Base Fee:
//! - Default: 0.01 XLM (100,000 stroops)
//! - Admin can update via set_base_fee() to adjust all action fees proportionally
//!
//! Auto-stake (invest/mine only):
//! - stake_amount = Minted reward amount per action
//! - Pulls newly minted HITZ from caller to contract for locking
//! - Updates per-user and total stake for entry

mod hitz_token;

use soroban_sdk::{
    contract, contractimpl, contracttype, Address, Env, String, Symbol, Vec, symbol_short, token, log, BytesN,
};

// The SkyhitzTokenClient is generated by the #[contract] macro in hitz_token.rs
use crate::hitz_token::SkyhitzTokenClient;

// ============================================================================
// Data Types
// ============================================================================

#[contracttype]
pub enum DataKey {
    // Instance storage (singleton config)
    Admin,
    Treasury,
    HitzToken,
    XlmToken,
    BaseFee,                            // Base fee per difficulty unit (default 0.01 XLM)
    
    // Persistent storage
    Entry(String),                      // Entry data
    Stake((String, Address)),           // Per-user stake: (entry_id, owner) -> amount
    StakeTotal(String),                 // Total staked per entry
    RewardPool(String),                 // HITZ rewards allocated to entry
    Claimed((String, Address)),         // HITZ rewards claimed by user
    EntryAt(u32),                       // Index -> entry_id for pagination
    EntryCount,                         // Total entry count
}

// Legacy storage keys from the previous core contract version.
// This enum mirrors the shape of the old contract's keys so we can delete them safely.
#[contracttype]
pub enum LegacyDataKey {
    Index,                  // persistent: Vec<String>
    Entries(String),        // persistent: Entry-like struct (legacy)
    Network,                // instance: String ("public" | "testnet")
    Admin,                  // instance: Address
}

#[contracttype]
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Entry {
    pub tvl_xlm: i128,      // Total Value Locked (equity-bearing)
    pub escrow_xlm: i128,   // Non-equity revenue
    pub created_at: u64,    // Timestamp
}

#[contract]
pub struct SkyhitzCore;

// ============================================================================
// Implementation
// ============================================================================

#[contractimpl]
impl SkyhitzCore {
    /// Upgrade core contract to new WASM code (admin-only)
    /// Note: Named `upgrade_core` to avoid export name collision with token's `upgrade`.
    pub fn upgrade_core(e: Env, new_wasm_hash: BytesN<32>) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap_or_else(|| panic!("Admin not set"));
        admin.require_auth();
        e.deployer().update_current_contract_wasm(new_wasm_hash);
    }

    /// Reset storage for both legacy and current keys (admin-only)
    ///
    /// Intended for use immediately after upgrading from the legacy contract,
    /// to wipe old state while keeping the same contract ID.
    /// Safe to call even if some keys don't exist.
    pub fn reset_all(e: Env) {
        // Require current admin if set; if not set (fresh upgrade), fall back to legacy admin.
        if let Some(admin) = e.storage().instance().get::<DataKey, Address>(&DataKey::Admin) {
            admin.require_auth();
        } else if let Some(legacy_admin) = e.storage().instance().get::<LegacyDataKey, Address>(&LegacyDataKey::Admin) {
            legacy_admin.require_auth();
        } else {
            panic!("No admin found to authorize reset");
        }

        // ---- Remove legacy instance keys ----
        if e.storage().instance().has(&LegacyDataKey::Admin) {
            e.storage().instance().remove(&LegacyDataKey::Admin);
        }
        if e.storage().instance().has(&LegacyDataKey::Network) {
            e.storage().instance().remove(&LegacyDataKey::Network);
        }

        // ---- Remove legacy persistent keys (Index + Entries) ----
        if let Some(index) = e.storage().persistent().get::<LegacyDataKey, Vec<String>>(&LegacyDataKey::Index) {
            for id in index.iter() {
                let key = LegacyDataKey::Entries(id.clone());
                if e.storage().persistent().has(&key) {
                    e.storage().persistent().remove(&key);
                }
            }
            e.storage().persistent().remove(&LegacyDataKey::Index);
        }

        // ---- Remove current instance keys if present ----
        if e.storage().instance().has(&DataKey::Admin) { e.storage().instance().remove(&DataKey::Admin); }
        if e.storage().instance().has(&DataKey::Treasury) { e.storage().instance().remove(&DataKey::Treasury); }
        if e.storage().instance().has(&DataKey::HitzToken) { e.storage().instance().remove(&DataKey::HitzToken); }
        if e.storage().instance().has(&DataKey::XlmToken) { e.storage().instance().remove(&DataKey::XlmToken); }
        if e.storage().instance().has(&DataKey::BaseFee) { e.storage().instance().remove(&DataKey::BaseFee); }

        // ---- Remove current persistent keys if present (entries and indexes) ----
        if let Some(count) = e.storage().instance().get::<DataKey, u32>(&DataKey::EntryCount) {
            // Remove EntryAt(i) and their Entry records
            for i in 0..count {
                let at_key = DataKey::EntryAt(i);
                if let Some(entry_id) = e.storage().persistent().get::<DataKey, String>(&at_key) {
                    let entry_key = DataKey::Entry(entry_id.clone());
                    if e.storage().persistent().has(&entry_key) {
                        e.storage().persistent().remove(&entry_key);
                    }
                    // Best-effort cleanup for reward pool and totals
                    let pool_key = DataKey::RewardPool(entry_id.clone());
                    if e.storage().persistent().has(&pool_key) { e.storage().persistent().remove(&pool_key); }
                    let total_key = DataKey::StakeTotal(entry_id.clone());
                    if e.storage().persistent().has(&total_key) { e.storage().persistent().remove(&total_key); }
                    // Claimed and Stake are keyed by (entry_id, user); we don't have a user index, so skip.
                }
                if e.storage().persistent().has(&at_key) {
                    e.storage().persistent().remove(&at_key);
                }
            }
            // Finally, remove EntryCount
            e.storage().instance().remove(&DataKey::EntryCount);
        }
    }
    /// Initialize the contract (one-time only)
    ///
    /// # Arguments
    /// * `admin` - Admin address with privileged rights
    /// * `treasury` - Treasury address receiving all XLM fees
    /// * `hitz_token` - HITZ token contract address (OpenZeppelin token)
    /// * `xlm_token` - XLM token contract address (SAC)
    /// * `base_fee` - Base fee per difficulty unit in stroops (default 100,000 = 0.01 XLM)
    pub fn init(
        e: Env,
        admin: Address,
        treasury: Address,
        hitz_token: Address,
        xlm_token: Address,
        base_fee: i128,
    ) {
        if e.storage().instance().has(&DataKey::Admin) {
            panic!("Already initialized");
        }

        e.storage().instance().set(&DataKey::Admin, &admin);
        e.storage().instance().set(&DataKey::Treasury, &treasury);
        e.storage().instance().set(&DataKey::HitzToken, &hitz_token);
        e.storage().instance().set(&DataKey::XlmToken, &xlm_token);
        e.storage().instance().set(&DataKey::BaseFee, &base_fee);
        e.storage().instance().set(&DataKey::EntryCount, &0u32);
    }

    /// Update base fee (admin-only)
    ///
    /// # Arguments
    /// * `new_base_fee` - New base fee per difficulty unit in stroops (e.g., 100,000 = 0.01 XLM)
    pub fn set_base_fee(e: Env, new_base_fee: i128) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        if new_base_fee < 0 {
            panic!("Base fee must be non-negative");
        }

        e.storage().instance().set(&DataKey::BaseFee, &new_base_fee);
    }

    /// Get current base fee
    pub fn get_base_fee(e: Env) -> i128 {
        e.storage().instance().get(&DataKey::BaseFee).unwrap_or(100_000)
    }

    /// Create a new entry (admin-only)
    pub fn create_entry(e: Env, entry_id: String) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        let entry_key = DataKey::Entry(entry_id.clone());
        if e.storage().persistent().has(&entry_key) {
            panic!("Entry already exists");
        }

        let now = e.ledger().timestamp();
        let entry = Entry {
            tvl_xlm: 0,
            escrow_xlm: 0,
            created_at: now,
        };

        e.storage().persistent().set(&entry_key, &entry);

        // Add to index
        let count: u32 = e.storage().instance().get(&DataKey::EntryCount).unwrap_or(0);
        e.storage().persistent().set(&DataKey::EntryAt(count), &entry_id);
        e.storage().instance().set(&DataKey::EntryCount, &(count + 1));
    }

    /// Record a user action (main entrypoint)
    ///
    /// Handles fee transfer, reward calculation, and optional auto-staking
    /// For invest action, amount_xlm specifies the investment (min 0.3 XLM), ignored for other actions
    pub fn record_action(e: Env, caller: Address, entry_id: String, kind: Symbol, amount_xlm: Option<i128>) {
        caller.require_auth();

        // Get action parameters
        let (fee, difficulty, adds_to_tvl, requires_stake) = get_action_params(&e, &kind, amount_xlm);

        // Load entry
        let entry_key = DataKey::Entry(entry_id.clone());
        let mut entry: Entry = e
            .storage()
            .persistent()
            .get(&entry_key)
            .unwrap_or_else(|| panic!("Entry not found"));

        // Transfer XLM fee from caller to Treasury
        let treasury: Address = e.storage().instance().get(&DataKey::Treasury).unwrap();
        let xlm_token: Address = e.storage().instance().get(&DataKey::XlmToken).unwrap();
        let xlm_client = token::Client::new(&e, &xlm_token);
        xlm_client.transfer(&caller, &treasury, &fee);

        // Attribute fee to entry
        if adds_to_tvl {
            entry.tvl_xlm = entry.tvl_xlm.saturating_add(fee);
        } else {
            entry.escrow_xlm = entry.escrow_xlm.saturating_add(fee);
        }

        // Request HITZ reward from token contract (handles emission logic)
        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_token_client = SkyhitzTokenClient::new(&e, &hitz_token);
        let owner = e.current_contract_address();
        let reward = hitz_token_client.mint_reward(&owner, &caller, &difficulty);

        // Auto-stake for invest/mine using the freshly minted reward amount
        if requires_stake {
            let stake_amt = reward;

            if stake_amt > 0 {
                // Transfer minted reward from user to contract to lock it as stake
                let hitz_client = token::Client::new(&e, &hitz_token);
                hitz_client.transfer(&caller, &e.current_contract_address(), &stake_amt);

                // Update stake maps using the newly staked reward amount
                let stake_key = DataKey::Stake((entry_id.clone(), caller.clone()));
                let current_stake: i128 = e.storage().persistent().get(&stake_key).unwrap_or(0);
                e.storage()
                    .persistent()
                    .set(&stake_key, &current_stake.saturating_add(stake_amt));

                let total_key = DataKey::StakeTotal(entry_id.clone());
                let current_total: i128 = e.storage().persistent().get(&total_key).unwrap_or(0);
                e.storage()
                    .persistent()
                    .set(&total_key, &current_total.saturating_add(stake_amt));

                log!(
                    &e,
                    "Stake: {} staked {} HITZ for entry {}",
                    caller,
                    stake_amt,
                    entry_id
                );
            }
        }

        // Save entry
        e.storage().persistent().set(&entry_key, &entry);

        log!(
            &e,
            "Action: {} - {} - fee: {} XLM, reward: {} HITZ",
            kind,
            entry_id,
            fee,
            reward
        );
    }

    // ========================================================================
    // View Functions
    // ========================================================================

    /// Get entry data
    pub fn get_entry(e: Env, entry_id: String) -> Option<Entry> {
        let key = DataKey::Entry(entry_id);
        e.storage().persistent().get(&key)
    }

    /// List entry IDs with pagination
    pub fn list_entries(e: Env, start: u32, limit: u32) -> Vec<String> {
        let count: u32 = e.storage().instance().get(&DataKey::EntryCount).unwrap_or(0);
        let mut result = Vec::new(&e);

        let end = start.saturating_add(limit).min(count);
        for i in start..end {
            if let Some(entry_id) = e.storage().persistent().get::<DataKey, String>(&DataKey::EntryAt(i)) {
                result.push_back(entry_id);
            }
        }

        result
    }

    /// Get user's stake for an entry
    pub fn get_stake(e: Env, entry_id: String, owner: Address) -> i128 {
        let key = DataKey::Stake((entry_id, owner));
        e.storage().persistent().get(&key).unwrap_or(0)
    }

    /// Get total stake for an entry
    pub fn get_stake_total(e: Env, entry_id: String) -> i128 {
        let key = DataKey::StakeTotal(entry_id);
        e.storage().persistent().get(&key).unwrap_or(0)
    }

    /// Contract version

    /// Distribute HITZ rewards proportionally based on escrow performance
    ///
    /// Treasury bot calls this after buying HITZ with accumulated XLM fees.
    /// Contract automatically distributes to entries based on their escrow_xlm.
    /// 
    /// # Arguments
    /// * `caller` - Treasury address that holds the HITZ
    /// * `hitz_amount` - Total HITZ to distribute across all entries
    /// 
    /// # Performance
    /// Optimized to single loop - O(n) where n = number of entries
    /// Handles rounding dust by allocating to last entry
    pub fn distribute_rewards(e: Env, caller: Address, hitz_amount: i128) {
        caller.require_auth();

        // Verify caller is the Treasury
        let treasury: Address = e.storage().instance().get(&DataKey::Treasury).unwrap();
        if caller != treasury {
            panic!("Only Treasury can distribute rewards");
        }
        if hitz_amount <= 0 {
            panic!("Amount must be positive");
        }

        // Transfer HITZ from Treasury to contract
        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_client = token::Client::new(&e, &hitz_token);
        hitz_client.transfer(&caller, &e.current_contract_address(), &hitz_amount);

        let entry_count: u32 = e.storage().instance().get(&DataKey::EntryCount).unwrap_or(0);
        
        // OPTIMIZED: Single-loop algorithm
        // First pass: collect entries with escrow and calculate total
        let mut entries_with_escrow: Vec<(String, i128)> = Vec::new(&e);
        let mut total_escrow: i128 = 0;
        
        for i in 0..entry_count {
            let index_key = DataKey::EntryAt(i);
            e.storage().persistent().extend_ttl(&index_key, 100, 535_680);
            
            if let Some(entry_id) = e.storage().persistent().get::<DataKey, String>(&index_key) {
                let entry_key = DataKey::Entry(entry_id.clone());
                e.storage().persistent().extend_ttl(&entry_key, 100, 535_680);
                
                if let Some(entry) = e.storage().persistent().get::<DataKey, Entry>(&entry_key) {
                    if entry.escrow_xlm > 0 {
                        total_escrow = total_escrow.saturating_add(entry.escrow_xlm);
                        entries_with_escrow.push_back((entry_id, entry.escrow_xlm));
                    }
                }
            }
        }

        if total_escrow == 0 {
            panic!("No escrow to distribute to");
        }

        // Distribute rewards and track remainder for dust
        let mut distributed_total: i128 = 0;
        let entries_len: u32 = entries_with_escrow.len();
        
        for (idx, (entry_id, escrow)) in entries_with_escrow.iter().enumerate() {
            let pool_key = DataKey::RewardPool(entry_id.clone());
            e.storage().persistent().extend_ttl(&pool_key, 100, 535_680);
            
            // Calculate share with rounding
            let mut entry_share = (hitz_amount.saturating_mul(escrow))
                .checked_div(total_escrow)
                .unwrap_or(0);
            
            // Give remaining dust to last entry to avoid losing tokens
            if (idx as u32) == entries_len - 1 {
                entry_share = entry_share.saturating_add(hitz_amount.saturating_sub(distributed_total).saturating_sub(entry_share));
            }
            
            if entry_share > 0 {
                let current_pool: i128 = e.storage().persistent().get(&pool_key).unwrap_or(0);
                e.storage().persistent().set(&pool_key, &current_pool.saturating_add(entry_share));
                distributed_total = distributed_total.saturating_add(entry_share);

                log!(
                    &e,
                    "Distributed {} HITZ to entry {} ({}% of total)",
                    entry_share,
                    entry_id,
                    (escrow * 100) / total_escrow
                );
            }
        }
    }

    /// Allocate HITZ rewards to a specific entry's reward pool
    ///
    /// Admin-only function for manual reward allocation (e.g., promotions, bonuses)
    pub fn allocate_rewards(e: Env, entry_id: String, hitz_amount: i128) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        // Verify entry exists
        let entry_key = DataKey::Entry(entry_id.clone());
        if !e.storage().persistent().has(&entry_key) {
            panic!("Entry not found");
        }

        if hitz_amount <= 0 {
            panic!("Amount must be positive");
        }

        // Transfer HITZ from admin/treasury to contract
        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_client = token::Client::new(&e, &hitz_token);
        hitz_client.transfer(&admin, &e.current_contract_address(), &hitz_amount);

        // Add to entry's reward pool
        let pool_key = DataKey::RewardPool(entry_id.clone());
        let current_pool: i128 = e.storage().persistent().get(&pool_key).unwrap_or(0);
        let new_pool = current_pool.saturating_add(hitz_amount);
        e.storage().persistent().set(&pool_key, &new_pool);

        log!(
            &e,
            "Rewards allocated: {} HITZ added to entry {} pool",
            hitz_amount,
            entry_id
        );
    }

    /// Batch allocate rewards to multiple entries
    ///
    /// Admin-only function for manual batch allocation (e.g., campaigns, airdrops)
    pub fn batch_allocate_rewards(e: Env, entry_ids: Vec<String>, amounts: Vec<i128>) {
        let admin: Address = e.storage().instance().get(&DataKey::Admin).unwrap();
        admin.require_auth();

        let len = entry_ids.len();
        if len != amounts.len() {
            panic!("Entry IDs and amounts length mismatch");
        }
        
        // Limit batch size to prevent gas issues
        if len > 100 {
            panic!("Batch size limited to 100 entries");
        }

        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_client = token::Client::new(&e, &hitz_token);

        for i in 0..len {
            let entry_id = entry_ids.get(i).unwrap();
            let hitz_amount = amounts.get(i).unwrap();
            
            if hitz_amount <= 0 {
                continue;
            }

            // Transfer HITZ to contract
            hitz_client.transfer(&admin, &e.current_contract_address(), &hitz_amount);

            // Add to reward pool with TTL extension
            let pool_key = DataKey::RewardPool(entry_id.clone());
            e.storage().persistent().extend_ttl(&pool_key, 100, 535_680);
            let current_pool: i128 = e.storage().persistent().get(&pool_key).unwrap_or(0);
            e.storage().persistent().set(&pool_key, &current_pool.saturating_add(hitz_amount));
        }
    }

    /// Claim HITZ rewards from an entry's reward pool
    ///
    /// Stakers receive rewards proportional to their stake
    /// Formula: claimable = (reward_pool × user_stake) / total_stake - already_claimed
    pub fn claim_rewards(e: Env, entry_id: String, claimer: Address) -> i128 {
        claimer.require_auth();

        // Get user's stake
        let stake_key = DataKey::Stake((entry_id.clone(), claimer.clone()));
        let user_stake: i128 = e.storage().persistent().get(&stake_key).unwrap_or(0);

        if user_stake == 0 {
            panic!("No stake in this entry");
        }

        // Get total stake
        let total_stake_key = DataKey::StakeTotal(entry_id.clone());
        let total_stake: i128 = e.storage().persistent().get(&total_stake_key).unwrap_or(0);

        if total_stake == 0 {
            panic!("No total stake found");
        }

        // Get reward pool
        let pool_key = DataKey::RewardPool(entry_id.clone());
        let reward_pool: i128 = e.storage().persistent().get(&pool_key).unwrap_or(0);

        if reward_pool == 0 {
            panic!("No rewards available");
        }

        // Calculate total claimable: (pool × user_stake) / total_stake
        let total_claimable = (reward_pool
            .saturating_mul(user_stake))
            .checked_div(total_stake)
            .unwrap_or(0);

        // Get already claimed
        let claimed_key = DataKey::Claimed((entry_id.clone(), claimer.clone()));
        let already_claimed: i128 = e.storage().persistent().get(&claimed_key).unwrap_or(0);

        // Calculate amount to claim
        let to_claim = total_claimable.saturating_sub(already_claimed);

        if to_claim <= 0 {
            panic!("No rewards to claim");
        }

        // Update claimed amount
        e.storage().persistent().set(&claimed_key, &already_claimed.saturating_add(to_claim));

        // Transfer HITZ rewards to claimer
        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_client = token::Client::new(&e, &hitz_token);
        hitz_client.transfer(&e.current_contract_address(), &claimer, &to_claim);

        log!(
            &e,
            "Rewards claimed: {} claimed {} HITZ from entry {}",
            claimer,
            to_claim,
            entry_id
        );

        to_claim
    }

    /// Unstake HITZ tokens from an entry
    ///
    /// Allows users to withdraw their staked HITZ back to their wallet.
    /// User loses their stake percentage and future rewards from this entry.
    /// 
    /// # Arguments
    /// * `entry_id` - The entry to unstake from
    /// * `caller` - The user unstaking (must have stake)
    /// * `amount` - Amount of HITZ to unstake (in stroops)
    /// 
    /// # Returns
    /// Amount unstaked
    /// 
    /// # Panics
    /// - If user has no stake
    /// - If amount exceeds user's stake
    /// - If amount <= 0
    pub fn unstake(e: Env, entry_id: String, caller: Address, amount: i128) -> i128 {
        caller.require_auth();
        
        // Validate amount
        if amount <= 0 {
            panic!("Amount must be positive");
        }
        
        // Get user's current stake
        let stake_key = DataKey::Stake((entry_id.clone(), caller.clone()));
        let user_stake: i128 = e.storage().persistent().get(&stake_key).unwrap_or(0);
        
        if user_stake == 0 {
            panic!("No stake in this entry");
        }
        
        if amount > user_stake {
            panic!("Amount exceeds stake");
        }
        
        e.storage().persistent().extend_ttl(&stake_key, 100, 535_680);
        
        // Update user's stake
        let new_user_stake = user_stake.saturating_sub(amount);
        if new_user_stake == 0 {
            // Remove stake entry if going to zero
            e.storage().persistent().remove(&stake_key);
        } else {
            e.storage().persistent().set(&stake_key, &new_user_stake);
        }
        
        // Update total stake
        let total_key = DataKey::StakeTotal(entry_id.clone());
        e.storage().persistent().extend_ttl(&total_key, 100, 535_680);
        let total_stake: i128 = e.storage().persistent().get(&total_key).unwrap_or(0);
        let new_total = total_stake.saturating_sub(amount);
        e.storage().persistent().set(&total_key, &new_total);
        
        // Transfer HITZ back to user
        let hitz_token: Address = e.storage().instance().get(&DataKey::HitzToken).unwrap();
        let hitz_client = token::Client::new(&e, &hitz_token);
        hitz_client.transfer(&e.current_contract_address(), &caller, &amount);
        
        log!(
            &e,
            "Unstake: {} withdrew {} HITZ from entry {}",
            caller,
            amount,
            entry_id
        );
        
        amount
    }

    /// Get claimable HITZ rewards for a user
    pub fn get_claimable_rewards(e: Env, entry_id: String, user: Address) -> i128 {
        let stake_key = DataKey::Stake((entry_id.clone(), user.clone()));
        let user_stake: i128 = e.storage().persistent().get(&stake_key).unwrap_or(0);

        if user_stake == 0 {
            return 0;
        }

        let total_stake: i128 = e.storage().persistent()
            .get(&DataKey::StakeTotal(entry_id.clone()))
            .unwrap_or(0);

        if total_stake == 0 {
            return 0;
        }

        let reward_pool: i128 = e.storage().persistent()
            .get(&DataKey::RewardPool(entry_id.clone()))
            .unwrap_or(0);

        // Calculate total claimable
        let total_claimable = (reward_pool
            .saturating_mul(user_stake))
            .checked_div(total_stake)
            .unwrap_or(0);

        // Subtract already claimed
        let claimed_key = DataKey::Claimed((entry_id.clone(), user.clone()));
        let already_claimed: i128 = e.storage().persistent().get(&claimed_key).unwrap_or(0);

        total_claimable.saturating_sub(already_claimed)
    }

    /// Get reward pool size for an entry
    pub fn get_reward_pool(e: Env, entry_id: String) -> i128 {
        let pool_key = DataKey::RewardPool(entry_id.clone());
        e.storage().persistent().get(&pool_key).unwrap_or(0)
    }

    /// Calculate APR for an entry based on HITZ rewards
    ///
    /// APR = ((reward_pool / total_stake) / days_since_creation) × 365 × 100
    /// Returns APR as basis points (1% = 100, 10% = 1000)
    pub fn calculate_apr(e: Env, entry_id: String) -> i128 {
        let entry_key = DataKey::Entry(entry_id.clone());
        let entry: Entry = match e.storage().persistent().get(&entry_key) {
            Some(e) => e,
            None => return 0,
        };

        // Get total stake (denominator)
        let total_stake: i128 = e.storage().persistent()
            .get(&DataKey::StakeTotal(entry_id.clone()))
            .unwrap_or(0);

        if total_stake == 0 {
            return 0;
        }

        // Get reward pool (numerator)
        let reward_pool: i128 = e.storage().persistent()
            .get(&DataKey::RewardPool(entry_id.clone()))
            .unwrap_or(0);

        // Calculate days since creation
        let now = e.ledger().timestamp();
        let seconds_elapsed = now.saturating_sub(entry.created_at);
        let days_elapsed = seconds_elapsed / 86_400;

        if days_elapsed == 0 {
            return 0;
        }

        // APR = (rewards / stake / days) × 365 × 10000 (basis points)
        // Example: 10% APR = 1000 basis points
        let daily_return = (reward_pool * 10_000) / total_stake;
        let annual_return = (daily_return * 365) / days_elapsed as i128;

        annual_return
    }

    /// Get comprehensive entry statistics for ranking
    ///
    /// Returns: (tvl_xlm, escrow_xlm, total_stake_hitz, reward_pool_hitz, apr_basis_points)
    pub fn get_entry_stats(e: Env, entry_id: String) -> (i128, i128, i128, i128, i128) {
        let entry_key = DataKey::Entry(entry_id.clone());
        let entry: Entry = match e.storage().persistent().get(&entry_key) {
            Some(e) => e,
            None => return (0, 0, 0, 0, 0),
        };

        let total_stake: i128 = e.storage().persistent()
            .get(&DataKey::StakeTotal(entry_id.clone()))
            .unwrap_or(0);

        let reward_pool: i128 = e.storage().persistent()
            .get(&DataKey::RewardPool(entry_id.clone()))
            .unwrap_or(0);

        let apr = Self::calculate_apr(e.clone(), entry_id);

        (entry.tvl_xlm, entry.escrow_xlm, total_stake, reward_pool, apr)
    }


    pub fn version() -> u32 {
        1
    }
}

// ============================================================================
// Helper Functions
// ============================================================================

/// Returns (fee, difficulty, adds_to_tvl, requires_stake) for an action kind
/// For invest action, amount_xlm determines the fee and proportional difficulty
/// For other actions, fee = base_fee * difficulty
fn get_action_params(e: &Env, kind: &Symbol, amount_xlm: Option<i128>) -> (i128, i128, bool, bool) {
    let stream = symbol_short!("stream");
    let like = symbol_short!("like");
    let download = symbol_short!("download");
    let mine = symbol_short!("mine");
    let invest = symbol_short!("invest");

    // Get base fee from storage (default 0.01 XLM)
    let base_fee: i128 = e.storage().instance().get(&DataKey::BaseFee).unwrap_or(100_000);

    if kind == &stream {
        let difficulty = 1;
        (base_fee * difficulty, difficulty, false, false)
    } else if kind == &like {
        let difficulty = 2;
        (base_fee * difficulty, difficulty, false, false)
    } else if kind == &download {
        let difficulty = 3;
        (base_fee * difficulty, difficulty, false, false)
    } else if kind == &mine {
        let difficulty = 10;
        (base_fee * difficulty, difficulty, true, true)
    } else if kind == &invest {
        // Dynamic investment: user specifies amount (min 0.3 XLM)
        let investment_amount = amount_xlm.unwrap_or(3_000_000);
        
        // Validate minimum investment
        if investment_amount < 3_000_000 {
            panic!("Minimum investment is 0.3 XLM (3,000,000 stroops)");
        }
        
        // Calculate proportional difficulty: 10 units per 1 XLM
        // This maintains reward parity with the original fixed invest action
        let difficulty = (investment_amount * 10) / 10_000_000;
        
        (investment_amount, difficulty, true, true)
    } else {
        panic!("Unknown action kind");
    }
}


// ============================================================================
// Tests
// ============================================================================

#[cfg(test)]
mod test {
    use super::*;
    use soroban_sdk::{testutils::{Address as _, Ledger}, Env};
    use crate::hitz_token::SkyhitzToken;

    fn setup_test() -> (Env, Address, Address, Address, Address, Address) {
        let e = Env::default();
        e.mock_all_auths();

        let admin = Address::generate(&e);
        let treasury = Address::generate(&e);
        let user = Address::generate(&e);
        
        // Deploy OpenZeppelin HITZ token with constructor args
        let hitz_token_id = e.register(SkyhitzToken, (
            admin.clone(),
            0u64,              // halving_start_ts
            126_144_000u64,    // halving_interval_sec (4 years)
            3_000_000i128,     // epoch0_unit_reward (0.3 HITZ)
        ));
        
        // Keep XLM as SAC for now (could also migrate to OpenZeppelin later)
        let xlm_token = e.register_stellar_asset_contract_v2(admin.clone());

        (e, admin, treasury, user, hitz_token_id, xlm_token.address())
    }

    // Helper function to get OpenZeppelin HITZ token client
    fn get_hitz_client<'a>(e: &'a Env, hitz_token_id: &'a Address) -> SkyhitzTokenClient<'a> {
        SkyhitzTokenClient::new(e, hitz_token_id)
    }

    #[test]
    fn test_init() {
        let (e, admin, treasury, _, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        let (epoch, unit_reward, released, remaining) = hitz_client.emission_info();
        assert_eq!(epoch, 0);
        assert_eq!(unit_reward, 3_000_000);
        assert_eq!(released, 0);
        assert_eq!(remaining, 210_000_000_000_000); // 21M HITZ
    }

    #[test]
    fn test_create_entry() {
        let (e, admin, treasury, _, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 0);
        assert_eq!(entry.escrow_xlm, 0);
    }

    #[test]
    fn test_record_action_stream() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        // Fund contract with HITZ using OpenZeppelin token
        let hitz_client = get_hitz_client(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &100_000_000i128);

        // Fund user with XLM
        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,    // stake_unit_hitz
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Record stream action
        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);

        // Check entry updated
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.escrow_xlm, 100_000); // 0.01 XLM fee added to escrow
        assert_eq!(entry.tvl_xlm, 0);

        // Check XLM transferred to treasury
        let treasury_xlm = token::Client::new(&e, &xlm_addr).balance(&treasury);
        assert_eq!(treasury_xlm, 100_000);

        // Check HITZ reward (difficulty 1 * 3M unit reward)
        let user_hitz = token::Client::new(&e, &hitz_addr).balance(&user);
        assert_eq!(user_hitz, 3_000_000);

        // Check released total
        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        let (_, _, released, _) = hitz_client.emission_info();
        assert_eq!(released, 3_000_000);
    }

    #[test]
    fn test_record_action_mine_with_stake() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        // Fund contract with HITZ using OpenZeppelin token admin mint
        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &1_000_000_000i128);

        // Fund user with XLM; HITZ balance not required for staking anymore
        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,   // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Record mine action (difficulty 10, requires stake)
        client.record_action(&user, &entry_id, &symbol_short!("mine"), &None);

        // Check entry updated (TVL not escrow)
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 10_000_000); // 1.0 XLM to TVL
        assert_eq!(entry.escrow_xlm, 0);

        // Check user balance (minted reward was auto-staked, so balance unchanged)
        let user_hitz = token::Client::new(&e, &hitz_addr).balance(&user);
        assert_eq!(user_hitz, 1_000_000_000);

        // Check stake recorded (equals minted reward amount)
        let stake = client.get_stake(&entry_id, &user);
        assert_eq!(stake, 30_000_000);

        let stake_total = client.get_stake_total(&entry_id);
        assert_eq!(stake_total, 30_000_000);
    }

    #[test]
    fn test_halving() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &1_000_000_000i128);
        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        // Start at timestamp 0, 4-year intervals
        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Epoch 0: full reward
        e.ledger().with_mut(|li| li.timestamp = 0);
        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        let (epoch, unit_reward, _, _) = hitz_client.emission_info();
        assert_eq!(epoch, 0);
        assert_eq!(unit_reward, 3_000_000);

        // Epoch 1: halved reward (after 4 years)
        e.ledger().with_mut(|li| li.timestamp = 126_144_000);
        let (epoch, unit_reward, _, _) = hitz_client.emission_info();
        assert_eq!(epoch, 1);
        assert_eq!(unit_reward, 1_500_000); // 3M / 2

        // Epoch 2: halved again
        e.ledger().with_mut(|li| li.timestamp = 2 * 126_144_000);
        let (epoch, unit_reward, _, _) = hitz_client.emission_info();
        assert_eq!(epoch, 2);
        assert_eq!(unit_reward, 750_000); // 3M / 4
    }

    #[test]
    fn test_supply_cap() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        // Fund contract with less than reward
        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &1_000_000i128); // Only 1M

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);

        // Should only get 1M (contract balance cap)
        let user_hitz = token::Client::new(&e, &hitz_addr).balance(&user);
        assert_eq!(user_hitz, 1_000_000);
    }

    #[test]
    fn test_list_entries() {
        let (e, admin, treasury, _, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        client.create_entry(&String::from_str(&e, "song1"));
        client.create_entry(&String::from_str(&e, "song2"));
        client.create_entry(&String::from_str(&e, "song3"));

        let entries = client.list_entries(&0, &10);
        assert_eq!(entries.len(), 3);
        assert_eq!(entries.get(0).unwrap(), String::from_str(&e, "song1"));
        assert_eq!(entries.get(1).unwrap(), String::from_str(&e, "song2"));
        assert_eq!(entries.get(2).unwrap(), String::from_str(&e, "song3"));

        // Test pagination
        let page = client.list_entries(&1, &2);
        assert_eq!(page.len(), 2);
        assert_eq!(page.get(0).unwrap(), String::from_str(&e, "song2"));
    }

    #[test]
    #[should_panic(expected = "Unknown action kind")]
    fn test_unknown_action_panics() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,    // stake_unit_hitz
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        client.record_action(&user, &entry_id, &symbol_short!("unknown"), &None);
    }

    #[test]
    fn test_multiple_action_kinds() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &1_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);
        hitz_admin.mint(&user, &1_000_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,    // stake_unit_hitz
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Stream, like, download -> escrow
        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);
        client.record_action(&user, &entry_id, &symbol_short!("like"), &None);
        client.record_action(&user, &entry_id, &symbol_short!("download"), &None);

        let entry = client.get_entry(&entry_id).unwrap();
        // 0.1 + 0.2 + 0.3 = 0.6 XLM = 6M stroops
        assert_eq!(entry.escrow_xlm, 6_000_000);
        assert_eq!(entry.tvl_xlm, 0);

        // Invest -> TVL (default 0.3 XLM)
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &None);

        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.escrow_xlm, 6_000_000);
        assert_eq!(entry.tvl_xlm, 3_000_000); // 0.3 XLM
    }

    #[test]
    fn test_dynamic_investment() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &1_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,   // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Test 1: Minimum investment (0.3 XLM = 3M stroops)
        // Difficulty = (3M * 10) / 10M = 3
        // Reward = 3 × unit reward (3_000_000) = 9_000_000 HITZ staked
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(3_000_000i128));
        
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 3_000_000); // 0.3 XLM
        
        let stake1 = client.get_stake(&entry_id, &user);
        assert_eq!(stake1, 9_000_000);

        // Test 2: Double investment (0.6 XLM = 6M stroops)
        // Difficulty = (6M * 10) / 10M = 6
        // Reward = 6 × unit reward (3_000_000) = 18_000_000 HITZ staked (total 27_000_000)
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(6_000_000i128));
        
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 9_000_000); // 0.3 + 0.6 = 0.9 XLM
        
        let stake2 = client.get_stake(&entry_id, &user);
        assert_eq!(stake2, 27_000_000);

        // Test 3: Large investment (3.0 XLM = 30M stroops)
        // Difficulty = (30M * 10) / 10M = 30
        // Reward = 30 × unit reward (3_000_000) = 90_000_000 HITZ staked (total 117_000_000)
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(30_000_000i128));
        
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 39_000_000); // 0.9 + 3.0 = 3.9 XLM
        
        let stake3 = client.get_stake(&entry_id, &user);
        assert_eq!(stake3, 117_000_000);

        // Verify proportional stakes
        let total_stake = client.get_stake_total(&entry_id);
        assert_eq!(total_stake, 117_000_000);
    }

    #[test]
    #[should_panic(expected = "Minimum investment is 0.3 XLM")]
    fn test_investment_below_minimum() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Should panic: 0.2 XLM is below minimum
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(2_000_000i128));
    }

    #[test]
    fn test_base_fee_modification() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_admin.admin_mint(&admin, &contract_id, &1_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,       // base_fee: 0.01 XLM
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Test 1: Default base fee (0.01 XLM)
        assert_eq!(client.get_base_fee(), 100_000);

        // Record a stream action with default base fee (0.01 XLM * 1 difficulty = 0.01 XLM)
        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.escrow_xlm, 100_000); // 0.01 XLM

        // Test 2: Update base fee to 0.02 XLM
        client.set_base_fee(&200_000i128);
        assert_eq!(client.get_base_fee(), 200_000);

        // Record another stream action (0.02 XLM * 1 difficulty = 0.02 XLM)
        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.escrow_xlm, 300_000); // 0.01 + 0.02 = 0.03 XLM

        // Test 3: Update base fee to 0.005 XLM
        client.set_base_fee(&50_000i128);
        assert_eq!(client.get_base_fee(), 50_000);

        // Record a like action (0.005 XLM * 2 difficulty = 0.01 XLM)
        client.record_action(&user, &entry_id, &symbol_short!("like"), &None);
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.escrow_xlm, 400_000); // 0.03 + 0.01 = 0.04 XLM

        // Verify mine action also respects new base fee (0.005 XLM * 10 difficulty = 0.05 XLM)
        hitz_admin.admin_mint(&admin, &user, &1_000_000_000i128);
        client.record_action(&user, &entry_id, &symbol_short!("mine"), &None);
        let entry = client.get_entry(&entry_id).unwrap();
        assert_eq!(entry.tvl_xlm, 50_000); // 0.05 XLM in TVL
    }

    #[test]
    #[should_panic(expected = "Base fee must be non-negative")]
    fn test_negative_base_fee() {
        let (e, admin, treasury, _, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,    // stake_unit_hitz
            &100_000i128,       // base_fee: 0.01 XLM
        );

        // Should panic: negative fee
        client.set_base_fee(&-1_000_000i128);
    }

    #[test]
    fn test_allocate_and_claim_rewards() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &1_000_000_000i128);
        hitz_admin.mint(&user, &1_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128); // For reward allocation

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User stakes by investing
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        let user_stake = client.get_stake(&entry_id, &user);
        assert_eq!(user_stake, 30_000_000);

        // Admin allocates 1000 HITZ as rewards
        client.allocate_rewards(&entry_id, &1_000_000_000i128);

        // Check reward pool
        let pool = client.get_reward_pool(&entry_id);
        assert_eq!(pool, 1_000_000_000);

        // Check claimable rewards (should be 100% since user has all stake)
        let claimable = client.get_claimable_rewards(&entry_id, &user);
        assert_eq!(claimable, 1_000_000_000);

        // User claims rewards
        let claimed = client.claim_rewards(&entry_id, &user);
        assert_eq!(claimed, 1_000_000_000);

        // Check claimable is now 0
        let claimable_after = client.get_claimable_rewards(&entry_id, &user);
        assert_eq!(claimable_after, 0);

        // User should have received HITZ
        let user_hitz = token::Client::new(&e, &hitz_addr).balance(&user);
        // Minted reward staked (30M) and claimed reward (1000M) increase balance by 1,030M
        assert_eq!(user_hitz, 1_030_000_000);
    }

    #[test]
    fn test_proportional_reward_distribution() {
        let (e, admin, treasury, _, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &10_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);

        // Create 3 users
        let user1 = Address::generate(&e);
        let user2 = Address::generate(&e);
        let user3 = Address::generate(&e);

        hitz_admin.mint(&user1, &10_000_000_000i128);
        hitz_admin.mint(&user2, &10_000_000_000i128);
        hitz_admin.mint(&user3, &10_000_000_000i128);

        xlm_admin.mint(&user1, &100_000_000i128);
        xlm_admin.mint(&user2, &100_000_000i128);
        xlm_admin.mint(&user3, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User1 invests 1 XLM (10 difficulty) → reward 30M HITZ stake
        client.record_action(&user1, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));
        
        // User2 invests 2 XLM (20 difficulty) → reward 60M HITZ stake
        client.record_action(&user2, &entry_id, &symbol_short!("invest"), &Some(20_000_000i128));
        
        // User3 invests 1 XLM (10 difficulty) → reward 30M HITZ stake
        client.record_action(&user3, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        // Total stake: 120M HITZ
        let total_stake = client.get_stake_total(&entry_id);
        assert_eq!(total_stake, 120_000_000);

        // Admin allocates 2000 HITZ rewards
        client.allocate_rewards(&entry_id, &2_000_000_000i128);

        // Check proportional claimable amounts
        let claimable1 = client.get_claimable_rewards(&entry_id, &user1);
        let claimable2 = client.get_claimable_rewards(&entry_id, &user2);
        let claimable3 = client.get_claimable_rewards(&entry_id, &user3);

        // User1: 30M / 120M = 25% → 500M HITZ (allocation unchanged)
        assert_eq!(claimable1, 500_000_000);
        
        // User2: 60M / 120M = 50% → 1000M HITZ
        assert_eq!(claimable2, 1_000_000_000);
        
        // User3: 30M / 120M = 25% → 500M HITZ
        assert_eq!(claimable3, 500_000_000);

        // Users claim
        client.claim_rewards(&entry_id, &user1);
        client.claim_rewards(&entry_id, &user2);
        client.claim_rewards(&entry_id, &user3);

        // Verify balances
        let balance1 = token::Client::new(&e, &hitz_addr).balance(&user1);
        let balance2 = token::Client::new(&e, &hitz_addr).balance(&user2);
        let balance3 = token::Client::new(&e, &hitz_addr).balance(&user3);

        // Each started with 10B, got action rewards, and claimed; minted rewards were staked, not deducted
        // User1: 10B + 30M action + 500M claim = 10,530M
        assert_eq!(balance1, 10_530_000_000);
        
        // User2: 10B + 60M action + 1000M claim = 11,060M
        assert_eq!(balance2, 11_060_000_000);
        
        // User3: 10B + 30M action + 500M claim = 10,530M
        assert_eq!(balance3, 10_530_000_000);
    }

    #[test]
    fn test_batch_allocate_rewards() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &10_000_000_000i128);
        hitz_admin.mint(&user, &10_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &1_000_000i128,
        );

        // Create 3 entries
        let entry1 = String::from_str(&e, "song1");
        let entry2 = String::from_str(&e, "song2");
        let entry3 = String::from_str(&e, "song3");
        
        client.create_entry(&entry1);
        client.create_entry(&entry2);
        client.create_entry(&entry3);

        // User stakes in all entries (stake equals minted reward per action)
        client.record_action(&user, &entry1, &symbol_short!("invest"), &Some(10_000_000i128));
        client.record_action(&user, &entry2, &symbol_short!("invest"), &Some(10_000_000i128));
        client.record_action(&user, &entry3, &symbol_short!("invest"), &Some(10_000_000i128));

        // Batch allocate rewards
        let mut entry_ids = Vec::new(&e);
        entry_ids.push_back(entry1.clone());
        entry_ids.push_back(entry2.clone());
        entry_ids.push_back(entry3.clone());

        let mut amounts = Vec::new(&e);
        amounts.push_back(100_000_000i128);
        amounts.push_back(200_000_000i128);
        amounts.push_back(300_000_000i128);

        client.batch_allocate_rewards(&entry_ids, &amounts);

        // Verify reward pools
        assert_eq!(client.get_reward_pool(&entry1), 100_000_000);
        assert_eq!(client.get_reward_pool(&entry2), 200_000_000);
        assert_eq!(client.get_reward_pool(&entry3), 300_000_000);
    }

    #[test]
    fn test_apr_calculation() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &10_000_000_000i128);
        hitz_admin.mint(&user, &10_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        // Set ledger time to day 0
        e.ledger().with_mut(|li| li.timestamp = 0);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests 10 XLM (100 difficulty)
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(100_000_000i128));

        let stake = client.get_stake(&entry_id, &user);
        assert_eq!(stake, 300_000_000);

        // Admin allocates 500M HITZ rewards on day 30
        e.ledger().with_mut(|li| li.timestamp = 30 * 86_400);
        client.allocate_rewards(&entry_id, &500_000_000i128);

        // Calculate APR
        // APR = (500M / 300M / 30 days) * 365 * 10000
        // APR = (1.666... / 30) * 365 * 10000 ≈ 202,833 basis points = 2028.33%
        let apr = client.calculate_apr(&entry_id);
        assert_eq!(apr, 202_833);

        // Test with more rewards on day 60
        e.ledger().with_mut(|li| li.timestamp = 60 * 86_400);
        client.allocate_rewards(&entry_id, &500_000_000i128);

        // Total rewards: 1000M over 60 days
        // APR = (1000M / 300M / 60 days) * 365 * 10000 ≈ 202,833 basis points
        let apr2 = client.calculate_apr(&entry_id);
        assert_eq!(apr2, 202_833);
    }

    #[test]
    fn test_get_entry_stats() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &10_000_000_000i128);
        hitz_admin.mint(&user, &10_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        e.ledger().with_mut(|li| li.timestamp = 0);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests (adds to TVL)
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        // Simulate user actions that add to escrow
        client.record_action(&user, &entry_id, &symbol_short!("stream"), &None);
        client.record_action(&user, &entry_id, &symbol_short!("like"), &None);

        // Allocate rewards
        e.ledger().with_mut(|li| li.timestamp = 30 * 86_400);
        client.allocate_rewards(&entry_id, &100_000_000i128);

        // Get stats
        let (tvl, escrow, stake, pool, apr) = client.get_entry_stats(&entry_id);

        assert_eq!(tvl, 10_000_000); // 10 XLM invested
        assert_eq!(escrow, 3_000_000); // 0.1 + 0.2 = 0.3 XLM from stream + like
        assert_eq!(stake, 30_000_000);
        assert_eq!(pool, 100_000_000); // 100M HITZ allocated
        
        // APR = (100M / 30M / 30 days) * 365 * 10000 ≈ 405,666 basis points
        assert_eq!(apr, 405_666);
    }

    #[test]
    #[should_panic(expected = "No stake in this entry")]
    fn test_claim_without_stake() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        client.allocate_rewards(&entry_id, &100_000_000i128);

        // Should panic: user has no stake
        client.claim_rewards(&entry_id, &user);
    }

    #[test]
    #[should_panic(expected = "No rewards to claim")]
    fn test_double_claim() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_admin = token::StellarAssetClient::new(&e, &hitz_addr);
        hitz_admin.mint(&contract_id, &10_000_000_000i128);
        hitz_admin.mint(&user, &10_000_000_000i128);
        hitz_admin.mint(&admin, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &1_000_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));
        client.allocate_rewards(&entry_id, &100_000_000i128);

        // First claim succeeds
        client.claim_rewards(&entry_id, &user);

        // Second claim should panic
        client.claim_rewards(&entry_id, &user);
    }

    #[test]
    fn test_unstake_partial() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);

        let hitz_balance_client = token::Client::new(&e, &hitz_addr);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests 10 XLM; minted reward (30M) is auto-staked
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        let user_stake_before = client.get_stake(&entry_id, &user);
        let total_stake_before = client.get_stake_total(&entry_id);
        assert_eq!(user_stake_before, 30_000_000);
        assert_eq!(total_stake_before, 30_000_000);

        let user_balance_before = hitz_balance_client.balance(&user);

        // Unstake 12M HITZ (40% of 30M stake)
        let unstaked = client.unstake(&entry_id, &user, &12_000_000i128);
        assert_eq!(unstaked, 12_000_000);

        // Verify stake updated
        let user_stake_after = client.get_stake(&entry_id, &user);
        let total_stake_after = client.get_stake_total(&entry_id);
        assert_eq!(user_stake_after, 18_000_000);
        assert_eq!(total_stake_after, 18_000_000);

        // Verify HITZ returned to user
        let user_balance_after = hitz_balance_client.balance(&user);
        assert_eq!(user_balance_after, user_balance_before + 12_000_000);
    }

    #[test]
    fn test_unstake_full() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests 10 XLM; minted reward (30M) is auto-staked
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        let user_stake_before = client.get_stake(&entry_id, &user);
        assert_eq!(user_stake_before, 30_000_000);

        // Unstake ALL HITZ
        let unstaked = client.unstake(&entry_id, &user, &30_000_000i128);
        assert_eq!(unstaked, 30_000_000);

        // Verify stake removed
        let user_stake_after = client.get_stake(&entry_id, &user);
        let total_stake_after = client.get_stake_total(&entry_id);
        assert_eq!(user_stake_after, 0);
        assert_eq!(total_stake_after, 0);
    }

    #[test]
    #[should_panic(expected = "No stake in this entry")]
    fn test_unstake_no_stake() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Try to unstake without any stake
        client.unstake(&entry_id, &user, &100_000_000i128);
    }

    #[test]
    #[should_panic(expected = "Amount exceeds stake")]
    fn test_unstake_exceeds_stake() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests 10 XLM → gets 500M HITZ stake
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        // Try to unstake MORE than staked
        client.unstake(&entry_id, &user, &600_000_000i128);
    }

    #[test]
    #[should_panic(expected = "Amount must be positive")]
    fn test_unstake_zero_amount() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));

        // Try to unstake 0
        client.unstake(&entry_id, &user, &0i128);
    }

    #[test]
    fn test_unstake_multiple_users() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();
        let user2 = Address::generate(&e);

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user2, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);
        xlm_admin.mint(&user2, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // Both users invest
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));
        client.record_action(&user2, &entry_id, &symbol_short!("invest"), &Some(20_000_000i128));

        // Total stake = 500M + 1000M = 1500M
        let total_stake_before = client.get_stake_total(&entry_id);
        assert_eq!(total_stake_before, 1_500_000_000);

        // User1 unstakes part of their stake (half of 15M = 7.5M)
        client.unstake(&entry_id, &user, &7_500_000i128);

        // Verify individual stakes
        let user1_stake = client.get_stake(&entry_id, &user);
        let user2_stake = client.get_stake(&entry_id, &user2);
        assert_eq!(user1_stake, 7_500_000);
        assert_eq!(user2_stake, 60_000_000);

        // Verify total stake
        let total_stake_after = client.get_stake_total(&entry_id);
        assert_eq!(total_stake_after, 67_500_000);
    }

    #[test]
    fn test_unstake_then_reinvest() {
        let (e, admin, treasury, user, hitz_addr, xlm_addr) = setup_test();

        let contract_id = e.register(SkyhitzCore, ());
        let client = SkyhitzCoreClient::new(&e, &contract_id);

        let hitz_client = SkyhitzTokenClient::new(&e, &hitz_addr);
        hitz_client.admin_mint(&admin, &contract_id, &10_000_000_000i128);
        hitz_client.admin_mint(&admin, &user, &10_000_000_000i128);

        let xlm_admin = token::StellarAssetClient::new(&e, &xlm_addr);
        xlm_admin.mint(&user, &100_000_000i128);

        client.init(
            &admin,
            &treasury,
            &hitz_addr,
            &xlm_addr,
            &50_000_000i128,
            &100_000i128,
        );

        let entry_id = String::from_str(&e, "song123");
        client.create_entry(&entry_id);

        // User invests
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));
        assert_eq!(client.get_stake(&entry_id, &user), 30_000_000);

        // User unstakes
        client.unstake(&entry_id, &user, &30_000_000i128);
        assert_eq!(client.get_stake(&entry_id, &user), 0);

        // User reinvests
        client.record_action(&user, &entry_id, &symbol_short!("invest"), &Some(10_000_000i128));
        assert_eq!(client.get_stake(&entry_id, &user), 30_000_000);
    }

}

